modLoader = "javafml"
loaderVersion = "[47,)"
license = "Custom"

[[mods]]
modId = "farm_and_charm"
version = "${version}"
displayName = "Farm Charm"
authors = "Your Name"
description = '''
Your Description'''
logoFile = "pack.png"

[[dependencies.farm_and_charm]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.farm_and_charm]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.farm_and_charm]]
modId = "doapi"
mandatory = true
versionRange = "[1.2.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.farm_and_charm]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"